package mapped;

// $VF: Compiled from av
public class Class348 {
   // $VF: synthetic field
   public static int field1014;
   // $VF: synthetic field
   public static int field1015;
   // $VF: synthetic field
   public static int field1016;
   // $VF: synthetic field
   public static int field1017;
   // $VF: synthetic field
   public static int field1018;
   // $VF: synthetic field
   public static int field1019;
   // $VF: synthetic field
   public static int field1020;
   // $VF: synthetic field
   public static int field1021;
   // $VF: synthetic field
   public static int field1022;
   // $VF: synthetic field
   public static int field1023;
   // $VF: synthetic field
   public static int field1024;
   // $VF: synthetic field
   public static int field1025;
   // $VF: synthetic field
   public static int field1026;
   // $VF: synthetic field
   public static int field1027;
   // $VF: synthetic field
   public static int field1028;
   // $VF: synthetic field
   public static int field1029;
   // $VF: synthetic field
   public static int field1030;
   // $VF: synthetic field
   public static int field1031;
   // $VF: synthetic field
   public static int field1032;
   // $VF: synthetic field
   public static int field1033;
   // $VF: synthetic field
   public static int field1034;
   // $VF: synthetic field
   public static int field1035;
   // $VF: synthetic field
   public static int field1036;
   // $VF: synthetic field
   public static int field1037;
   // $VF: synthetic field
   public static int field1038;
   // $VF: synthetic field
   public static int field1039;
   // $VF: synthetic field
   public static int field1040;
   // $VF: synthetic field
   public static int field1041;
   // $VF: synthetic field
   public static int field1042;
   // $VF: synthetic field
   public static int field1043;
   // $VF: synthetic field
   public static int field1044;
   // $VF: synthetic field
   public static int field1045;
   // $VF: synthetic field
   public static int field1046;
}
